async function test() {
  try {
    console.log(1);
  } catch (err) {
    console.log(err);
  }
}

/* async function test() {
  try{
    console.log(1);
  } catch(e) {
    //TODO handle the exception
  }
} */