async function test() {
    console.log(1);
}

/* async function test() {
  try{
    console.log(1);
  } catch(e) {
    //TODO handle the exception
  }
} */